## W0705 (duplicate-except)

### :x: Problematic code:

```python
# to be addded
```

### :heavy_check_mark: Correct code:

```python
# to be added
```

### Rationale:

 *Catching previously caught exception type %s*
  Used when an except catches a type that was already caught by a previous
  handler. This message belongs to the exceptions checker.



### Related resources:

- [Testcases](#)
- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22duplicate-except%22+OR+%22W0705%22)
