## W1622 (next-method-called)

### :x: Problematic code:

```python
data = iter(xrange(10))
data.next()
```

### :heavy_check_mark: Correct code:

```python
data = iter(range(10))
next(data)
```

### Rationale:

Used when an object's `next()` method is called (Python 3 uses the `next()`
built-in function).

### Related resources:

- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22next-method-called%22+OR+%22W1622%22)
