## E1700 (yield-inside-async-function)

### :x: Problematic code:

```python
# to be addded
```

### :heavy_check_mark: Correct code:

```python
# to be added
```

### Rationale:

 *Yield inside async function*
  Used when an `yield` or `yield from` statement is found inside an async
  function. This message belongs to the async checker. It can't be emitted when
  using Python < 3.5.



### Related resources:

- [Testcases](#)
- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22yield-inside-async-function%22+OR+%22E1700%22)
